# Generated by Django 2.1.4 on 2018-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
